extern "C" {

    #define NULL_POINTER_PASSED_FOR_BYTE_BUFFER -10L
    #define SIZE_PASSED_WAS_0_OR_NEGATIVE -9L
    #define MESSAGE_FAILED_TO_PARSE -8L
    #define BUFFER_TOO_SMALL_FOR_DEFAULT_MESSAGE -7L

}
