/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _GTypeQuery {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("type"),
        Constants$root.C_POINTER$LAYOUT.withName("type_name"),
        Constants$root.C_INT$LAYOUT.withName("class_size"),
        Constants$root.C_INT$LAYOUT.withName("instance_size")
    ).withName("_GTypeQuery");
    public static MemoryLayout $LAYOUT() {
        return _GTypeQuery.$struct$LAYOUT;
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return _GTypeQuery.type$VH;
    }
    public static long type$get(MemorySegment seg) {
        return (long)_GTypeQuery.type$VH.get(seg);
    }
    public static void type$set( MemorySegment seg, long x) {
        _GTypeQuery.type$VH.set(seg, x);
    }
    public static long type$get(MemorySegment seg, long index) {
        return (long)_GTypeQuery.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, long x) {
        _GTypeQuery.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle type_name$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type_name"));
    public static VarHandle type_name$VH() {
        return _GTypeQuery.type_name$VH;
    }
    public static MemoryAddress type_name$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_GTypeQuery.type_name$VH.get(seg);
    }
    public static void type_name$set( MemorySegment seg, MemoryAddress x) {
        _GTypeQuery.type_name$VH.set(seg, x);
    }
    public static MemoryAddress type_name$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_GTypeQuery.type_name$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type_name$set(MemorySegment seg, long index, MemoryAddress x) {
        _GTypeQuery.type_name$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle class_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("class_size"));
    public static VarHandle class_size$VH() {
        return _GTypeQuery.class_size$VH;
    }
    public static int class_size$get(MemorySegment seg) {
        return (int)_GTypeQuery.class_size$VH.get(seg);
    }
    public static void class_size$set( MemorySegment seg, int x) {
        _GTypeQuery.class_size$VH.set(seg, x);
    }
    public static int class_size$get(MemorySegment seg, long index) {
        return (int)_GTypeQuery.class_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void class_size$set(MemorySegment seg, long index, int x) {
        _GTypeQuery.class_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle instance_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("instance_size"));
    public static VarHandle instance_size$VH() {
        return _GTypeQuery.instance_size$VH;
    }
    public static int instance_size$get(MemorySegment seg) {
        return (int)_GTypeQuery.instance_size$VH.get(seg);
    }
    public static void instance_size$set( MemorySegment seg, int x) {
        _GTypeQuery.instance_size$VH.set(seg, x);
    }
    public static int instance_size$get(MemorySegment seg, long index) {
        return (int)_GTypeQuery.instance_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void instance_size$set(MemorySegment seg, long index, int x) {
        _GTypeQuery.instance_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


