/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _VipsArgumentClass {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("pspec")
        ).withName("parent"),
        Constants$root.C_POINTER$LAYOUT.withName("object_class"),
        Constants$root.C_INT$LAYOUT.withName("flags"),
        Constants$root.C_INT$LAYOUT.withName("priority"),
        Constants$root.C_INT$LAYOUT.withName("offset"),
        MemoryLayout.paddingLayout(32)
    ).withName("_VipsArgumentClass");
    public static MemoryLayout $LAYOUT() {
        return _VipsArgumentClass.$struct$LAYOUT;
    }
    public static MemorySegment parent$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    static final VarHandle object_class$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("object_class"));
    public static VarHandle object_class$VH() {
        return _VipsArgumentClass.object_class$VH;
    }
    public static MemoryAddress object_class$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsArgumentClass.object_class$VH.get(seg);
    }
    public static void object_class$set( MemorySegment seg, MemoryAddress x) {
        _VipsArgumentClass.object_class$VH.set(seg, x);
    }
    public static MemoryAddress object_class$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsArgumentClass.object_class$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void object_class$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsArgumentClass.object_class$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return _VipsArgumentClass.flags$VH;
    }
    public static int flags$get(MemorySegment seg) {
        return (int)_VipsArgumentClass.flags$VH.get(seg);
    }
    public static void flags$set( MemorySegment seg, int x) {
        _VipsArgumentClass.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)_VipsArgumentClass.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        _VipsArgumentClass.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle priority$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("priority"));
    public static VarHandle priority$VH() {
        return _VipsArgumentClass.priority$VH;
    }
    public static int priority$get(MemorySegment seg) {
        return (int)_VipsArgumentClass.priority$VH.get(seg);
    }
    public static void priority$set( MemorySegment seg, int x) {
        _VipsArgumentClass.priority$VH.set(seg, x);
    }
    public static int priority$get(MemorySegment seg, long index) {
        return (int)_VipsArgumentClass.priority$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void priority$set(MemorySegment seg, long index, int x) {
        _VipsArgumentClass.priority$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("offset"));
    public static VarHandle offset$VH() {
        return _VipsArgumentClass.offset$VH;
    }
    public static int offset$get(MemorySegment seg) {
        return (int)_VipsArgumentClass.offset$VH.get(seg);
    }
    public static void offset$set( MemorySegment seg, int x) {
        _VipsArgumentClass.offset$VH.set(seg, x);
    }
    public static int offset$get(MemorySegment seg, long index) {
        return (int)_VipsArgumentClass.offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset$set(MemorySegment seg, long index, int x) {
        _VipsArgumentClass.offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


