/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _VipsBufferCache {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("buffers"),
        Constants$root.C_POINTER$LAYOUT.withName("thread"),
        Constants$root.C_POINTER$LAYOUT.withName("im"),
        Constants$root.C_POINTER$LAYOUT.withName("buffer_thread"),
        Constants$root.C_POINTER$LAYOUT.withName("reserve"),
        Constants$root.C_INT$LAYOUT.withName("n_reserve"),
        MemoryLayout.paddingLayout(32)
    ).withName("_VipsBufferCache");
    public static MemoryLayout $LAYOUT() {
        return _VipsBufferCache.$struct$LAYOUT;
    }
    static final VarHandle buffers$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("buffers"));
    public static VarHandle buffers$VH() {
        return _VipsBufferCache.buffers$VH;
    }
    public static MemoryAddress buffers$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.buffers$VH.get(seg);
    }
    public static void buffers$set( MemorySegment seg, MemoryAddress x) {
        _VipsBufferCache.buffers$VH.set(seg, x);
    }
    public static MemoryAddress buffers$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.buffers$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void buffers$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsBufferCache.buffers$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle thread$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("thread"));
    public static VarHandle thread$VH() {
        return _VipsBufferCache.thread$VH;
    }
    public static MemoryAddress thread$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.thread$VH.get(seg);
    }
    public static void thread$set( MemorySegment seg, MemoryAddress x) {
        _VipsBufferCache.thread$VH.set(seg, x);
    }
    public static MemoryAddress thread$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.thread$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void thread$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsBufferCache.thread$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle im$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("im"));
    public static VarHandle im$VH() {
        return _VipsBufferCache.im$VH;
    }
    public static MemoryAddress im$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.im$VH.get(seg);
    }
    public static void im$set( MemorySegment seg, MemoryAddress x) {
        _VipsBufferCache.im$VH.set(seg, x);
    }
    public static MemoryAddress im$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.im$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void im$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsBufferCache.im$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle buffer_thread$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("buffer_thread"));
    public static VarHandle buffer_thread$VH() {
        return _VipsBufferCache.buffer_thread$VH;
    }
    public static MemoryAddress buffer_thread$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.buffer_thread$VH.get(seg);
    }
    public static void buffer_thread$set( MemorySegment seg, MemoryAddress x) {
        _VipsBufferCache.buffer_thread$VH.set(seg, x);
    }
    public static MemoryAddress buffer_thread$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.buffer_thread$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void buffer_thread$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsBufferCache.buffer_thread$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle reserve$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reserve"));
    public static VarHandle reserve$VH() {
        return _VipsBufferCache.reserve$VH;
    }
    public static MemoryAddress reserve$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.reserve$VH.get(seg);
    }
    public static void reserve$set( MemorySegment seg, MemoryAddress x) {
        _VipsBufferCache.reserve$VH.set(seg, x);
    }
    public static MemoryAddress reserve$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_VipsBufferCache.reserve$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reserve$set(MemorySegment seg, long index, MemoryAddress x) {
        _VipsBufferCache.reserve$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle n_reserve$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("n_reserve"));
    public static VarHandle n_reserve$VH() {
        return _VipsBufferCache.n_reserve$VH;
    }
    public static int n_reserve$get(MemorySegment seg) {
        return (int)_VipsBufferCache.n_reserve$VH.get(seg);
    }
    public static void n_reserve$set( MemorySegment seg, int x) {
        _VipsBufferCache.n_reserve$VH.set(seg, x);
    }
    public static int n_reserve$get(MemorySegment seg, long index) {
        return (int)_VipsBufferCache.n_reserve$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void n_reserve$set(MemorySegment seg, long index, int x) {
        _VipsBufferCache.n_reserve$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


