/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$117 {

    static final FunctionDescriptor vips_tracked_get_allocs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle vips_tracked_get_allocs$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_get_allocs",
        constants$117.vips_tracked_get_allocs$FUNC
    );
    static final FunctionDescriptor vips_tracked_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_tracked_open$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_open",
        constants$117.vips_tracked_open$FUNC
    );
    static final FunctionDescriptor vips_tracked_close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_tracked_close$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_close",
        constants$117.vips_tracked_close$FUNC
    );
    static final FunctionDescriptor vips_tracked_get_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle vips_tracked_get_files$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_get_files",
        constants$117.vips_tracked_get_files$FUNC
    );
    static final FunctionDescriptor vips_error_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_error_buffer$MH = RuntimeHelper.downcallHandle(
        "vips_error_buffer",
        constants$117.vips_error_buffer$FUNC
    );
    static final FunctionDescriptor vips_error_buffer_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_error_buffer_copy$MH = RuntimeHelper.downcallHandle(
        "vips_error_buffer_copy",
        constants$117.vips_error_buffer_copy$FUNC
    );
}


