/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$164 {

    static final FunctionDescriptor vips_svgload$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_svgload$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_svgload",
        constants$164.vips_svgload$FUNC
    );
    static final FunctionDescriptor vips_svgload_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_svgload_buffer$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_svgload_buffer",
        constants$164.vips_svgload_buffer$FUNC
    );
    static final FunctionDescriptor vips_svgload_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_svgload_string$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_svgload_string",
        constants$164.vips_svgload_string$FUNC
    );
    static final FunctionDescriptor vips_svgload_source$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_svgload_source$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_svgload_source",
        constants$164.vips_svgload_source$FUNC
    );
    static final FunctionDescriptor vips_gifload$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_gifload$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_gifload",
        constants$164.vips_gifload$FUNC
    );
    static final FunctionDescriptor vips_gifload_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_gifload_buffer$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_gifload_buffer",
        constants$164.vips_gifload_buffer$FUNC
    );
}


