/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$119 {

    static final FunctionDescriptor vips_verror_system$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_verror_system$MH = RuntimeHelper.downcallHandle(
        "vips_verror_system",
        constants$119.vips_verror_system$FUNC
    );
    static final FunctionDescriptor vips_error_g$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_error_g$MH = RuntimeHelper.downcallHandle(
        "vips_error_g",
        constants$119.vips_error_g$FUNC
    );
    static final FunctionDescriptor vips_g_error$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_g_error$MH = RuntimeHelper.downcallHandle(
        "vips_g_error",
        constants$119.vips_g_error$FUNC
    );
    static final FunctionDescriptor vips_error_exit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_error_exit$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_error_exit",
        constants$119.vips_error_exit$FUNC
    );
    static final FunctionDescriptor vips_check_uncoded$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_check_uncoded$MH = RuntimeHelper.downcallHandle(
        "vips_check_uncoded",
        constants$119.vips_check_uncoded$FUNC
    );
    static final FunctionDescriptor vips_check_coding$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_check_coding$MH = RuntimeHelper.downcallHandle(
        "vips_check_coding",
        constants$119.vips_check_coding$FUNC
    );
}


