/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$77 {

    static final FunctionDescriptor vips_value_get_array_object$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_value_get_array_object$MH = RuntimeHelper.downcallHandle(
        "vips_value_get_array_object",
        constants$77.vips_value_get_array_object$FUNC
    );
    static final FunctionDescriptor vips_value_set_array_object$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_value_set_array_object$MH = RuntimeHelper.downcallHandle(
        "vips_value_set_array_object",
        constants$77.vips_value_set_array_object$FUNC
    );
    static final  OfInt vips__thread_profile$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle vips__thread_profile$VH = constants$77.vips__thread_profile$LAYOUT.varHandle();
    static final MemorySegment vips__thread_profile$SEGMENT = RuntimeHelper.lookupGlobalVariable("vips__thread_profile", constants$77.vips__thread_profile$LAYOUT);
    static final FunctionDescriptor vips_profile_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_profile_set$MH = RuntimeHelper.downcallHandle(
        "vips_profile_set",
        constants$77.vips_profile_set$FUNC
    );
    static final FunctionDescriptor vips__thread_profile_attach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips__thread_profile_attach$MH = RuntimeHelper.downcallHandle(
        "vips__thread_profile_attach",
        constants$77.vips__thread_profile_attach$FUNC
    );
    static final FunctionDescriptor vips__thread_profile_detach$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle vips__thread_profile_detach$MH = RuntimeHelper.downcallHandle(
        "vips__thread_profile_detach",
        constants$77.vips__thread_profile_detach$FUNC
    );
}


