/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$135 {

    static final FunctionDescriptor VipsThreadpoolProgressFn$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VipsThreadpoolProgressFn$MH = RuntimeHelper.downcallHandle(
        constants$135.VipsThreadpoolProgressFn$FUNC
    );
    static final FunctionDescriptor vips_threadpool_run$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_threadpool_run$MH = RuntimeHelper.downcallHandle(
        "vips_threadpool_run",
        constants$135.vips_threadpool_run$FUNC
    );
    static final FunctionDescriptor vips_get_tile_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_get_tile_size$MH = RuntimeHelper.downcallHandle(
        "vips_get_tile_size",
        constants$135.vips_get_tile_size$FUNC
    );
    static final FunctionDescriptor vips_format_sizeof$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_format_sizeof$MH = RuntimeHelper.downcallHandle(
        "vips_format_sizeof",
        constants$135.vips_format_sizeof$FUNC
    );
    static final FunctionDescriptor vips_format_sizeof_unsafe$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_format_sizeof_unsafe$MH = RuntimeHelper.downcallHandle(
        "vips_format_sizeof_unsafe",
        constants$135.vips_format_sizeof_unsafe$FUNC
    );
    static final FunctionDescriptor vips_image_get_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_get_width$MH = RuntimeHelper.downcallHandle(
        "vips_image_get_width",
        constants$135.vips_image_get_width$FUNC
    );
}


