/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$111 {

    static final FunctionDescriptor vips_image_decode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_decode$MH = RuntimeHelper.downcallHandle(
        "vips_image_decode",
        constants$111.vips_image_decode$FUNC
    );
    static final FunctionDescriptor vips_image_encode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_image_encode$MH = RuntimeHelper.downcallHandle(
        "vips_image_encode",
        constants$111.vips_image_encode$FUNC
    );
    static final FunctionDescriptor vips_image_isMSBfirst$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_isMSBfirst$MH = RuntimeHelper.downcallHandle(
        "vips_image_isMSBfirst",
        constants$111.vips_image_isMSBfirst$FUNC
    );
    static final FunctionDescriptor vips_image_isfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_isfile$MH = RuntimeHelper.downcallHandle(
        "vips_image_isfile",
        constants$111.vips_image_isfile$FUNC
    );
    static final FunctionDescriptor vips_image_ispartial$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_ispartial$MH = RuntimeHelper.downcallHandle(
        "vips_image_ispartial",
        constants$111.vips_image_ispartial$FUNC
    );
    static final FunctionDescriptor vips_image_hasalpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_hasalpha$MH = RuntimeHelper.downcallHandle(
        "vips_image_hasalpha",
        constants$111.vips_image_hasalpha$FUNC
    );
}


