/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$226 {

    static final FunctionDescriptor vips_col_sRGB2scRGB_8$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_sRGB2scRGB_8$MH = RuntimeHelper.downcallHandle(
        "vips_col_sRGB2scRGB_8",
        constants$226.vips_col_sRGB2scRGB_8$FUNC
    );
    static final FunctionDescriptor vips_col_sRGB2scRGB_16$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_sRGB2scRGB_16$MH = RuntimeHelper.downcallHandle(
        "vips_col_sRGB2scRGB_16",
        constants$226.vips_col_sRGB2scRGB_16$FUNC
    );
    static final FunctionDescriptor vips_col_sRGB2scRGB_8_noclip$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_sRGB2scRGB_8_noclip$MH = RuntimeHelper.downcallHandle(
        "vips_col_sRGB2scRGB_8_noclip",
        constants$226.vips_col_sRGB2scRGB_8_noclip$FUNC
    );
    static final FunctionDescriptor vips_col_sRGB2scRGB_16_noclip$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_sRGB2scRGB_16_noclip$MH = RuntimeHelper.downcallHandle(
        "vips_col_sRGB2scRGB_16_noclip",
        constants$226.vips_col_sRGB2scRGB_16_noclip$FUNC
    );
    static final FunctionDescriptor vips_col_scRGB2XYZ$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_scRGB2XYZ$MH = RuntimeHelper.downcallHandle(
        "vips_col_scRGB2XYZ",
        constants$226.vips_col_scRGB2XYZ$FUNC
    );
    static final FunctionDescriptor vips_col_XYZ2scRGB$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_col_XYZ2scRGB$MH = RuntimeHelper.downcallHandle(
        "vips_col_XYZ2scRGB",
        constants$226.vips_col_XYZ2scRGB$FUNC
    );
}


