/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$109 {

    static final FunctionDescriptor vips_image_matrix_from_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_image_matrix_from_array$MH = RuntimeHelper.downcallHandle(
        "vips_image_matrix_from_array",
        constants$109.vips_image_matrix_from_array$FUNC
    );
    static final FunctionDescriptor vips_image_new_from_image$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_image_new_from_image$MH = RuntimeHelper.downcallHandle(
        "vips_image_new_from_image",
        constants$109.vips_image_new_from_image$FUNC
    );
    static final FunctionDescriptor vips_image_new_from_image1$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_image_new_from_image1$MH = RuntimeHelper.downcallHandle(
        "vips_image_new_from_image1",
        constants$109.vips_image_new_from_image1$FUNC
    );
    static final FunctionDescriptor vips_image_set_delete_on_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_image_set_delete_on_close$MH = RuntimeHelper.downcallHandle(
        "vips_image_set_delete_on_close",
        constants$109.vips_image_set_delete_on_close$FUNC
    );
    static final FunctionDescriptor vips_get_disc_threshold$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_get_disc_threshold$MH = RuntimeHelper.downcallHandle(
        "vips_get_disc_threshold",
        constants$109.vips_get_disc_threshold$FUNC
    );
    static final FunctionDescriptor vips_image_new_temp_file$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_image_new_temp_file$MH = RuntimeHelper.downcallHandle(
        "vips_image_new_temp_file",
        constants$109.vips_image_new_temp_file$FUNC
    );
}


