/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$124 {

    static final FunctionDescriptor vips_check_vector_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_check_vector_length$MH = RuntimeHelper.downcallHandle(
        "vips_check_vector_length",
        constants$124.vips_check_vector_length$FUNC
    );
    static final FunctionDescriptor vips_check_vector$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_check_vector$MH = RuntimeHelper.downcallHandle(
        "vips_check_vector",
        constants$124.vips_check_vector$FUNC
    );
    static final FunctionDescriptor vips_check_hist$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_check_hist$MH = RuntimeHelper.downcallHandle(
        "vips_check_hist",
        constants$124.vips_check_hist$FUNC
    );
    static final FunctionDescriptor vips_check_matrix$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_check_matrix$MH = RuntimeHelper.downcallHandle(
        "vips_check_matrix",
        constants$124.vips_check_matrix$FUNC
    );
    static final FunctionDescriptor vips_check_separable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_check_separable$MH = RuntimeHelper.downcallHandle(
        "vips_check_separable",
        constants$124.vips_check_separable$FUNC
    );
    static final FunctionDescriptor vips_check_precision_intfloat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_check_precision_intfloat$MH = RuntimeHelper.downcallHandle(
        "vips_check_precision_intfloat",
        constants$124.vips_check_precision_intfloat$FUNC
    );
}


