/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$100 {

    static final FunctionDescriptor im_lu_decomp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_lu_decomp$MH = RuntimeHelper.downcallHandle(
        "im_lu_decomp",
        constants$100.im_lu_decomp$FUNC
    );
    static final FunctionDescriptor im_lu_solve$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_lu_solve$MH = RuntimeHelper.downcallHandle(
        "im_lu_solve",
        constants$100.im_lu_solve$FUNC
    );
    static final FunctionDescriptor im_matinv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_matinv$MH = RuntimeHelper.downcallHandle(
        "im_matinv",
        constants$100.im_matinv$FUNC
    );
    static final FunctionDescriptor im_matinv_inplace$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_matinv_inplace$MH = RuntimeHelper.downcallHandle(
        "im_matinv_inplace",
        constants$100.im_matinv_inplace$FUNC
    );
    static final FunctionDescriptor im_local_dmask$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_local_dmask$MH = RuntimeHelper.downcallHandle(
        "im_local_dmask",
        constants$100.im_local_dmask$FUNC
    );
    static final FunctionDescriptor im_local_imask$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_local_imask$MH = RuntimeHelper.downcallHandle(
        "im_local_imask",
        constants$100.im_local_imask$FUNC
    );
}


