/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$116 {

    static final FunctionDescriptor vips_malloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle vips_malloc$MH = RuntimeHelper.downcallHandle(
        "vips_malloc",
        constants$116.vips_malloc$FUNC
    );
    static final FunctionDescriptor vips_strdup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_strdup$MH = RuntimeHelper.downcallHandle(
        "vips_strdup",
        constants$116.vips_strdup$FUNC
    );
    static final FunctionDescriptor vips_tracked_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_tracked_free$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_free",
        constants$116.vips_tracked_free$FUNC
    );
    static final FunctionDescriptor vips_tracked_malloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle vips_tracked_malloc$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_malloc",
        constants$116.vips_tracked_malloc$FUNC
    );
    static final FunctionDescriptor vips_tracked_get_mem$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_tracked_get_mem$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_get_mem",
        constants$116.vips_tracked_get_mem$FUNC
    );
    static final FunctionDescriptor vips_tracked_get_mem_highwater$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_tracked_get_mem_highwater$MH = RuntimeHelper.downcallHandle(
        "vips_tracked_get_mem_highwater",
        constants$116.vips_tracked_get_mem_highwater$FUNC
    );
}


