/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$15 {

    static final FunctionDescriptor g_type_add_class_cache_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_add_class_cache_func$MH = RuntimeHelper.downcallHandle(
        "g_type_add_class_cache_func",
        constants$15.g_type_add_class_cache_func$FUNC
    );
    static final FunctionDescriptor g_type_remove_class_cache_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_remove_class_cache_func$MH = RuntimeHelper.downcallHandle(
        "g_type_remove_class_cache_func",
        constants$15.g_type_remove_class_cache_func$FUNC
    );
    static final FunctionDescriptor g_type_class_unref_uncached$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_class_unref_uncached$MH = RuntimeHelper.downcallHandle(
        "g_type_class_unref_uncached",
        constants$15.g_type_class_unref_uncached$FUNC
    );
    static final FunctionDescriptor g_type_add_interface_check$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_add_interface_check$MH = RuntimeHelper.downcallHandle(
        "g_type_add_interface_check",
        constants$15.g_type_add_interface_check$FUNC
    );
    static final FunctionDescriptor g_type_remove_interface_check$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_type_remove_interface_check$MH = RuntimeHelper.downcallHandle(
        "g_type_remove_interface_check",
        constants$15.g_type_remove_interface_check$FUNC
    );
    static final FunctionDescriptor g_type_value_table_peek$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_type_value_table_peek$MH = RuntimeHelper.downcallHandle(
        "g_type_value_table_peek",
        constants$15.g_type_value_table_peek$FUNC
    );
}


