/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$235 {

    static final FunctionDescriptor im_video_test$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle im_video_test$MH = RuntimeHelper.downcallHandle(
        "im_video_test",
        constants$235.im_video_test$FUNC
    );
    static final FunctionDescriptor vips_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_init$MH = RuntimeHelper.downcallHandle(
        "vips_init",
        constants$235.vips_init$FUNC
    );
    static final FunctionDescriptor vips_get_argv0$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_get_argv0$MH = RuntimeHelper.downcallHandle(
        "vips_get_argv0",
        constants$235.vips_get_argv0$FUNC
    );
    static final FunctionDescriptor vips_get_prgname$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_get_prgname$MH = RuntimeHelper.downcallHandle(
        "vips_get_prgname",
        constants$235.vips_get_prgname$FUNC
    );
    static final FunctionDescriptor vips_shutdown$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle vips_shutdown$MH = RuntimeHelper.downcallHandle(
        "vips_shutdown",
        constants$235.vips_shutdown$FUNC
    );
    static final FunctionDescriptor vips_thread_shutdown$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle vips_thread_shutdown$MH = RuntimeHelper.downcallHandle(
        "vips_thread_shutdown",
        constants$235.vips_thread_shutdown$FUNC
    );
}


