/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$48 {

    static final FunctionDescriptor vips_dbuf_steal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_dbuf_steal$MH = RuntimeHelper.downcallHandle(
        "vips_dbuf_steal",
        constants$48.vips_dbuf_steal$FUNC
    );
    static final FunctionDescriptor vips_enum_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_enum_string$MH = RuntimeHelper.downcallHandle(
        "vips_enum_string",
        constants$48.vips_enum_string$FUNC
    );
    static final FunctionDescriptor vips_enum_nick$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_enum_nick$MH = RuntimeHelper.downcallHandle(
        "vips_enum_nick",
        constants$48.vips_enum_nick$FUNC
    );
    static final FunctionDescriptor vips_enum_from_nick$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_enum_from_nick$MH = RuntimeHelper.downcallHandle(
        "vips_enum_from_nick",
        constants$48.vips_enum_from_nick$FUNC
    );
    static final FunctionDescriptor vips_flags_from_nick$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_flags_from_nick$MH = RuntimeHelper.downcallHandle(
        "vips_flags_from_nick",
        constants$48.vips_flags_from_nick$FUNC
    );
    static final FunctionDescriptor vips_slist_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_slist_equal$MH = RuntimeHelper.downcallHandle(
        "vips_slist_equal",
        constants$48.vips_slist_equal$FUNC
    );
}


