/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$223 {

    static final FunctionDescriptor vips_icc_export$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_icc_export$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_icc_export",
        constants$223.vips_icc_export$FUNC
    );
    static final FunctionDescriptor vips_icc_ac2rc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_icc_ac2rc$MH = RuntimeHelper.downcallHandle(
        "vips_icc_ac2rc",
        constants$223.vips_icc_ac2rc$FUNC
    );
    static final FunctionDescriptor vips_icc_is_compatible_profile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle vips_icc_is_compatible_profile$MH = RuntimeHelper.downcallHandle(
        "vips_icc_is_compatible_profile",
        constants$223.vips_icc_is_compatible_profile$FUNC
    );
    static final FunctionDescriptor vips_dE76$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_dE76$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_dE76",
        constants$223.vips_dE76$FUNC
    );
    static final FunctionDescriptor vips_dE00$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_dE00$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_dE00",
        constants$223.vips_dE00$FUNC
    );
    static final FunctionDescriptor vips_dECMC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_dECMC$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_dECMC",
        constants$223.vips_dECMC$FUNC
    );
}


