/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$171 {

    static final FunctionDescriptor vips_precision_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_precision_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_precision_get_type",
        constants$171.vips_precision_get_type$FUNC
    );
    static final FunctionDescriptor vips_intent_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_intent_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_intent_get_type",
        constants$171.vips_intent_get_type$FUNC
    );
    static final FunctionDescriptor vips_pcs_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_pcs_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_pcs_get_type",
        constants$171.vips_pcs_get_type$FUNC
    );
    static final FunctionDescriptor vips_extend_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_extend_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_extend_get_type",
        constants$171.vips_extend_get_type$FUNC
    );
    static final FunctionDescriptor vips_compass_direction_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_compass_direction_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_compass_direction_get_type",
        constants$171.vips_compass_direction_get_type$FUNC
    );
    static final FunctionDescriptor vips_direction_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_direction_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_direction_get_type",
        constants$171.vips_direction_get_type$FUNC
    );
}


