/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$183 {

    static final FunctionDescriptor vips_cosh$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_cosh$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_cosh",
        constants$183.vips_cosh$FUNC
    );
    static final FunctionDescriptor vips_tanh$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_tanh$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_tanh",
        constants$183.vips_tanh$FUNC
    );
    static final FunctionDescriptor vips_asinh$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_asinh$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_asinh",
        constants$183.vips_asinh$FUNC
    );
    static final FunctionDescriptor vips_acosh$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_acosh$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_acosh",
        constants$183.vips_acosh$FUNC
    );
    static final FunctionDescriptor vips_atanh$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_atanh$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_atanh",
        constants$183.vips_atanh$FUNC
    );
    static final FunctionDescriptor vips_complex$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_complex$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_complex",
        constants$183.vips_complex$FUNC
    );
}


