/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$191 {

    static final FunctionDescriptor vips_boolean_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_boolean_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_boolean_const1",
        constants$191.vips_boolean_const1$FUNC
    );
    static final FunctionDescriptor vips_andimage_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_andimage_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_andimage_const1",
        constants$191.vips_andimage_const1$FUNC
    );
    static final FunctionDescriptor vips_orimage_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_orimage_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_orimage_const1",
        constants$191.vips_orimage_const1$FUNC
    );
    static final FunctionDescriptor vips_eorimage_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_eorimage_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_eorimage_const1",
        constants$191.vips_eorimage_const1$FUNC
    );
    static final FunctionDescriptor vips_lshift_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_lshift_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_lshift_const1",
        constants$191.vips_lshift_const1$FUNC
    );
    static final FunctionDescriptor vips_rshift_const1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle vips_rshift_const1$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_rshift_const1",
        constants$191.vips_rshift_const1$FUNC
    );
}


