/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$68 {

    static final FunctionDescriptor vips_class_map_all$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_class_map_all$MH = RuntimeHelper.downcallHandle(
        "vips_class_map_all",
        constants$68.vips_class_map_all$FUNC
    );
    static final FunctionDescriptor vips_class_find$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_class_find$MH = RuntimeHelper.downcallHandle(
        "vips_class_find",
        constants$68.vips_class_find$FUNC
    );
    static final FunctionDescriptor vips_object_local_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_object_local_array$MH = RuntimeHelper.downcallHandle(
        "vips_object_local_array",
        constants$68.vips_object_local_array$FUNC
    );
    static final FunctionDescriptor vips_object_local_cb$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_object_local_cb$MH = RuntimeHelper.downcallHandle(
        "vips_object_local_cb",
        constants$68.vips_object_local_cb$FUNC
    );
    static final FunctionDescriptor vips_object_set_static$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_object_set_static$MH = RuntimeHelper.downcallHandle(
        "vips_object_set_static",
        constants$68.vips_object_set_static$FUNC
    );
    static final FunctionDescriptor vips_object_print_all$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle vips_object_print_all$MH = RuntimeHelper.downcallHandle(
        "vips_object_print_all",
        constants$68.vips_object_print_all$FUNC
    );
}


