/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$90 {

    static final FunctionDescriptor vips_buffer_dump_all$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle vips_buffer_dump_all$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_dump_all",
        constants$90.vips_buffer_dump_all$FUNC
    );
    static final FunctionDescriptor vips_buffer_done$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buffer_done$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_done",
        constants$90.vips_buffer_done$FUNC
    );
    static final FunctionDescriptor vips_buffer_undone$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buffer_undone$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_undone",
        constants$90.vips_buffer_undone$FUNC
    );
    static final FunctionDescriptor vips_buffer_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buffer_unref$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_unref",
        constants$90.vips_buffer_unref$FUNC
    );
    static final FunctionDescriptor vips_buffer_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buffer_new$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_new",
        constants$90.vips_buffer_new$FUNC
    );
    static final FunctionDescriptor vips_buffer_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buffer_ref$MH = RuntimeHelper.downcallHandle(
        "vips_buffer_ref",
        constants$90.vips_buffer_ref$FUNC
    );
}


