/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$213 {

    static final FunctionDescriptor vips_hist_match$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_hist_match$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_hist_match",
        constants$213.vips_hist_match$FUNC
    );
    static final FunctionDescriptor vips_hist_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_hist_local$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_hist_local",
        constants$213.vips_hist_local$FUNC
    );
    static final FunctionDescriptor vips_hist_ismonotonic$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_hist_ismonotonic$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_hist_ismonotonic",
        constants$213.vips_hist_ismonotonic$FUNC
    );
    static final FunctionDescriptor vips_hist_entropy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_hist_entropy$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_hist_entropy",
        constants$213.vips_hist_entropy$FUNC
    );
    static final FunctionDescriptor vips_case$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_case$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_case",
        constants$213.vips_case$FUNC
    );
    static final FunctionDescriptor vips_fwfft$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_fwfft$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_fwfft",
        constants$213.vips_fwfft$FUNC
    );
}


