/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$96 {

    static final FunctionDescriptor im_write_dmask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_write_dmask$MH = RuntimeHelper.downcallHandle(
        "im_write_dmask",
        constants$96.im_write_dmask$FUNC
    );
    static final FunctionDescriptor im_write_imask_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_write_imask_name$MH = RuntimeHelper.downcallHandle(
        "im_write_imask_name",
        constants$96.im_write_imask_name$FUNC
    );
    static final FunctionDescriptor im_write_dmask_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_write_dmask_name$MH = RuntimeHelper.downcallHandle(
        "im_write_dmask_name",
        constants$96.im_write_dmask_name$FUNC
    );
    static final FunctionDescriptor im_free_imask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_free_imask$MH = RuntimeHelper.downcallHandle(
        "im_free_imask",
        constants$96.im_free_imask$FUNC
    );
    static final FunctionDescriptor im_free_dmask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle im_free_dmask$MH = RuntimeHelper.downcallHandle(
        "im_free_dmask",
        constants$96.im_free_dmask$FUNC
    );
    static final FunctionDescriptor im_log_imask$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle im_log_imask$MH = RuntimeHelper.downcallHandle(
        "im_log_imask",
        constants$96.im_log_imask$FUNC
    );
}


