/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$236 {

    static final FunctionDescriptor vips_add_option_entries$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_add_option_entries$MH = RuntimeHelper.downcallHandle(
        "vips_add_option_entries",
        constants$236.vips_add_option_entries$FUNC
    );
    static final FunctionDescriptor vips_leak_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_leak_set$MH = RuntimeHelper.downcallHandle(
        "vips_leak_set",
        constants$236.vips_leak_set$FUNC
    );
    static final FunctionDescriptor vips_block_untrusted_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_block_untrusted_set$MH = RuntimeHelper.downcallHandle(
        "vips_block_untrusted_set",
        constants$236.vips_block_untrusted_set$FUNC
    );
    static final FunctionDescriptor vips_version_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_version_string$MH = RuntimeHelper.downcallHandle(
        "vips_version_string",
        constants$236.vips_version_string$FUNC
    );
    static final FunctionDescriptor vips_version$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_version$MH = RuntimeHelper.downcallHandle(
        "vips_version",
        constants$236.vips_version$FUNC
    );
    static final FunctionDescriptor vips_guess_prefix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_guess_prefix$MH = RuntimeHelper.downcallHandle(
        "vips_guess_prefix",
        constants$236.vips_guess_prefix$FUNC
    );
}


