/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$31 {

    static final FunctionDescriptor g_object_get_valist$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_get_valist$MH = RuntimeHelper.downcallHandle(
        "g_object_get_valist",
        constants$31.g_object_get_valist$FUNC
    );
    static final FunctionDescriptor g_object_set_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_set_property$MH = RuntimeHelper.downcallHandle(
        "g_object_set_property",
        constants$31.g_object_set_property$FUNC
    );
    static final FunctionDescriptor g_object_get_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_get_property$MH = RuntimeHelper.downcallHandle(
        "g_object_get_property",
        constants$31.g_object_get_property$FUNC
    );
    static final FunctionDescriptor g_object_freeze_notify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_freeze_notify$MH = RuntimeHelper.downcallHandle(
        "g_object_freeze_notify",
        constants$31.g_object_freeze_notify$FUNC
    );
    static final FunctionDescriptor g_object_notify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_notify$MH = RuntimeHelper.downcallHandle(
        "g_object_notify",
        constants$31.g_object_notify$FUNC
    );
    static final FunctionDescriptor g_object_notify_by_pspec$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_notify_by_pspec$MH = RuntimeHelper.downcallHandle(
        "g_object_notify_by_pspec",
        constants$31.g_object_notify_by_pspec$FUNC
    );
}


