/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$44 {

    static final FunctionDescriptor vips_buf_append_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle vips_buf_append_size$MH = RuntimeHelper.downcallHandle(
        "vips_buf_append_size",
        constants$44.vips_buf_append_size$FUNC
    );
    static final FunctionDescriptor vips_buf_removec$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle vips_buf_removec$MH = RuntimeHelper.downcallHandle(
        "vips_buf_removec",
        constants$44.vips_buf_removec$FUNC
    );
    static final FunctionDescriptor vips_buf_change$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buf_change$MH = RuntimeHelper.downcallHandle(
        "vips_buf_change",
        constants$44.vips_buf_change$FUNC
    );
    static final FunctionDescriptor vips_buf_is_empty$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buf_is_empty$MH = RuntimeHelper.downcallHandle(
        "vips_buf_is_empty",
        constants$44.vips_buf_is_empty$FUNC
    );
    static final FunctionDescriptor vips_buf_is_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buf_is_full$MH = RuntimeHelper.downcallHandle(
        "vips_buf_is_full",
        constants$44.vips_buf_is_full$FUNC
    );
    static final FunctionDescriptor vips_buf_all$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_buf_all$MH = RuntimeHelper.downcallHandle(
        "vips_buf_all",
        constants$44.vips_buf_all$FUNC
    );
}


