/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$203 {

    static final FunctionDescriptor vips_cast_dpcomplex$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_cast_dpcomplex$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_cast_dpcomplex",
        constants$203.vips_cast_dpcomplex$FUNC
    );
    static final FunctionDescriptor vips_scale$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_scale$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_scale",
        constants$203.vips_scale$FUNC
    );
    static final FunctionDescriptor vips_msb$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_msb$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_msb",
        constants$203.vips_msb$FUNC
    );
    static final FunctionDescriptor vips_byteswap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_byteswap$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_byteswap",
        constants$203.vips_byteswap$FUNC
    );
    static final FunctionDescriptor vips_bandjoin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle vips_bandjoin$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_bandjoin",
        constants$203.vips_bandjoin$FUNC
    );
    static final FunctionDescriptor vips_bandjoin2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_bandjoin2$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_bandjoin2",
        constants$203.vips_bandjoin2$FUNC
    );
}


