/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$152 {

    static final FunctionDescriptor vips_foreign_load_invalidate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_foreign_load_invalidate$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_load_invalidate",
        constants$152.vips_foreign_load_invalidate$FUNC
    );
    static final FunctionDescriptor vips_foreign_save_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle vips_foreign_save_get_type$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_save_get_type",
        constants$152.vips_foreign_save_get_type$FUNC
    );
    static final FunctionDescriptor vips_foreign_find_save$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_foreign_find_save$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_find_save",
        constants$152.vips_foreign_find_save$FUNC
    );
    static final FunctionDescriptor vips_foreign_get_suffixes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_foreign_get_suffixes$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_get_suffixes",
        constants$152.vips_foreign_get_suffixes$FUNC
    );
    static final FunctionDescriptor vips_foreign_find_save_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_foreign_find_save_buffer$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_find_save_buffer",
        constants$152.vips_foreign_find_save_buffer$FUNC
    );
    static final FunctionDescriptor vips_foreign_find_save_target$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_foreign_find_save_target$MH = RuntimeHelper.downcallHandle(
        "vips_foreign_find_save_target",
        constants$152.vips_foreign_find_save_target$FUNC
    );
}


