/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$200 {

    static final FunctionDescriptor vips_rot90$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_rot90$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_rot90",
        constants$200.vips_rot90$FUNC
    );
    static final FunctionDescriptor vips_rot180$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_rot180$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_rot180",
        constants$200.vips_rot180$FUNC
    );
    static final FunctionDescriptor vips_rot270$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_rot270$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_rot270",
        constants$200.vips_rot270$FUNC
    );
    static final FunctionDescriptor vips_rot45$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_rot45$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_rot45",
        constants$200.vips_rot45$FUNC
    );
    static final FunctionDescriptor vips_autorot_remove_angle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_autorot_remove_angle$MH = RuntimeHelper.downcallHandle(
        "vips_autorot_remove_angle",
        constants$200.vips_autorot_remove_angle$FUNC
    );
    static final FunctionDescriptor vips_autorot$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_autorot$MH = RuntimeHelper.downcallHandleVariadic(
        "vips_autorot",
        constants$200.vips_autorot$FUNC
    );
}


