/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$130 {

    static final FunctionDescriptor vips_interpolate_get_window_offset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_interpolate_get_window_offset$MH = RuntimeHelper.downcallHandle(
        "vips_interpolate_get_window_offset",
        constants$130.vips_interpolate_get_window_offset$FUNC
    );
    static final FunctionDescriptor vips_interpolate_nearest_static$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_interpolate_nearest_static$MH = RuntimeHelper.downcallHandle(
        "vips_interpolate_nearest_static",
        constants$130.vips_interpolate_nearest_static$FUNC
    );
    static final FunctionDescriptor vips_interpolate_bilinear_static$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_interpolate_bilinear_static$MH = RuntimeHelper.downcallHandle(
        "vips_interpolate_bilinear_static",
        constants$130.vips_interpolate_bilinear_static$FUNC
    );
    static final FunctionDescriptor vips_interpolate_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_interpolate_new$MH = RuntimeHelper.downcallHandle(
        "vips_interpolate_new",
        constants$130.vips_interpolate_new$FUNC
    );
    static final FunctionDescriptor vips_g_mutex_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle vips_g_mutex_new$MH = RuntimeHelper.downcallHandle(
        "vips_g_mutex_new",
        constants$130.vips_g_mutex_new$FUNC
    );
    static final FunctionDescriptor vips_g_mutex_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vips_g_mutex_free$MH = RuntimeHelper.downcallHandle(
        "vips_g_mutex_free",
        constants$130.vips_g_mutex_free$FUNC
    );
}


