/*
 * jvips, a Java implementation that interfaces to libvips
 *
 * Copyright (C) 2023 Jonathan Strauss
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

// Generated by jextract

package org.libvips;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$21 {

    static final FunctionDescriptor g_signal_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_signal_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_name",
        constants$21.g_signal_name$FUNC
    );
    static final FunctionDescriptor g_signal_query$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_query$MH = RuntimeHelper.downcallHandle(
        "g_signal_query",
        constants$21.g_signal_query$FUNC
    );
    static final FunctionDescriptor g_signal_list_ids$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_list_ids$MH = RuntimeHelper.downcallHandle(
        "g_signal_list_ids",
        constants$21.g_signal_list_ids$FUNC
    );
    static final FunctionDescriptor g_signal_is_valid_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_is_valid_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_is_valid_name",
        constants$21.g_signal_is_valid_name$FUNC
    );
    static final FunctionDescriptor g_signal_parse_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_signal_parse_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_parse_name",
        constants$21.g_signal_parse_name$FUNC
    );
    static final FunctionDescriptor g_signal_get_invocation_hint$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_get_invocation_hint$MH = RuntimeHelper.downcallHandle(
        "g_signal_get_invocation_hint",
        constants$21.g_signal_get_invocation_hint$FUNC
    );
}


